export const MassPriceUpdateLabels = {
    updatePrices: 'Atualizar preços',
    selectCVS: 'Selecionar arquivo .CSV',
    quantityItems: 'Quantidade de itens',
    validate: 'Validar',
    update: 'Atualizar',
    warning: 'Aviso',
    code: 'Código',
    name: 'Nome',
    unit: 'Unidade',
    actualPrice: 'Preço atual',
    newPrice: 'Novo preço',
    hasNoCostPrice: 'Não há preço de custo',
    productNotFind: 'Produto não encontrado',
    hasNoNewPrice: 'Não há preço novo',
    newPriceInvalid: 'Novo preço está inválido',
    priceLowerThanCost: 'Novo preço menor que o preço de custo',
    priceHigherThanTenPercent: 'Novo preço excede a margem de 10%',
}